export const mock = [
  {
    idDrink: '16990',
    strDrink: 'Sweet Tooth',
    strDrinkAlternate: null,
    strDrinkES: null,
    strDrinkDE: null,
    strDrinkFR: null,
    'strDrinkZH-HANS': null,
    'strDrinkZH-HANT': null,
    strTags: null,
    strVideo: null,
    strCategory: 'Milk / Float / Shake',
    strIBA: null,
    strAlcoholic: 'Alcoholic',
    strGlass: 'Highball Glass',
    strInstructions:
      'Put 2 shots Godiva Liquour into a glass, add as much or as little milk as you would like.',
    strInstructionsES: null,
    strInstructionsDE:
      'Geben Sie 2 Spritzer Godiva Liquour in ein Glas, geben Sie so viel Milch hinzu, wie Sie möchten.',
    strInstructionsFR: null,
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb:
      'https://www.thecocktaildb.com/images/media/drink/j6rq6h1503563821.jpg',
    strIngredient1: 'Godiva liqueur',
    strIngredient2: 'Milk',
    strIngredient3: null,
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: '2 shots ',
    strMeasure2: null,
    strMeasure3: null,
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: 'No',
    dateModified: '2017-08-24 09:37:01',
  },
  {
    idDrink: '13625',
    strDrink: 'Screaming Orgasm',
    strDrinkAlternate: null,
    strDrinkES: null,
    strDrinkDE: null,
    strDrinkFR: null,
    'strDrinkZH-HANS': null,
    'strDrinkZH-HANT': null,
    strTags: null,
    strVideo: null,
    strCategory: 'Ordinary Drink',
    strIBA: null,
    strAlcoholic: 'Alcoholic',
    strGlass: 'Cocktail glass',
    strInstructions:
      "Pour first vodka, then Bailey's, then Kahlua into a cocktail glass over crushed ice. Stir. Caution: use only high quality vodka. Cheap vodka can cause the Bailey's to curdle. Test your brand of vodka by mixing 1 Tsp each of vodka and Bailey's first.",
    strInstructionsES: null,
    strInstructionsDE:
      "Gießen Sie zuerst Wodka, dann Bailey's, dann Kahlua in ein Cocktailglas über zerstoßenes Eis. Rühren. Achtung: Verwenden Sie nur hochwertigen Wodka. Billiger Wodka kann dazu führen, dass der Bailey's gerinnt. Testen Sie Ihre Wodka-Marke, indem Sie jeweils 1 Teelöffel Wodka und einen Teelöffel Bailey's mischen.",
    strInstructionsFR: null,
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb:
      'https://www.thecocktaildb.com/images/media/drink/x894cs1504388670.jpg',
    strIngredient1: 'Vodka',
    strIngredient2: 'Baileys irish cream',
    strIngredient3: 'Kahlua',
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: '1 oz ',
    strMeasure2: '1 1/2 oz ',
    strMeasure3: '1/2 oz ',
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: 'No',
    dateModified: '2017-09-02 22:44:30',
  },
  {
    idDrink: '14610',
    strDrink: 'ACID',
    strDrinkAlternate: null,
    strDrinkES: null,
    strDrinkDE: null,
    strDrinkFR: null,
    'strDrinkZH-HANS': null,
    'strDrinkZH-HANT': null,
    strTags: null,
    strVideo: null,
    strCategory: 'Shot',
    strIBA: null,
    strAlcoholic: 'Alcoholic',
    strGlass: 'Shot glass',
    strInstructions:
      'Poor in the 151 first followed by the 101 served with a Coke or Dr Pepper chaser.',
    strInstructionsES: null,
    strInstructionsDE:
      'Gering den 151 gefolgt von der 101, die mit einer Cola oder Dr. Pepper Chaser serviert wird.',
    strInstructionsFR: null,
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb:
      'https://www.thecocktaildb.com/images/media/drink/xuxpxt1479209317.jpg',
    strIngredient1: '151 proof rum',
    strIngredient2: 'Wild Turkey',
    strIngredient3: null,
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: '1 oz Bacardi ',
    strMeasure2: '1 oz ',
    strMeasure3: null,
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: 'No',
    dateModified: '2016-11-15 11:28:37',
  },
  {
    idDrink: '12698',
    strDrink: 'Lassi - Mango',
    strDrinkAlternate: null,
    strDrinkES: null,
    strDrinkDE: null,
    strDrinkFR: null,
    'strDrinkZH-HANS': null,
    'strDrinkZH-HANT': null,
    strTags: null,
    strVideo: null,
    strCategory: 'Other/Unknown',
    strIBA: null,
    strAlcoholic: 'Non alcoholic',
    strGlass: 'Highball glass',
    strInstructions:
      'Put it all in a blender and pour over crushed ice. You can also use other fruits like strawberries and bananas.',
    strInstructionsES: null,
    strInstructionsDE:
      'Alles in einen Mixer geben und über das zerstoßene Eis gießen. Du kannst auch andere Früchte wie Erdbeeren und Bananen verwenden.',
    strInstructionsFR: null,
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb:
      'https://www.thecocktaildb.com/images/media/drink/1bw6sd1487603816.jpg',
    strIngredient1: 'Mango',
    strIngredient2: 'Yoghurt',
    strIngredient3: 'Sugar',
    strIngredient4: 'Water',
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: '2 ',
    strMeasure2: '2 cups ',
    strMeasure3: '1/2 cup ',
    strMeasure4: '1 cup iced ',
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: 'No',
    dateModified: '2017-02-20 15:16:56',
  },
]
